spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: sql_prod
    password: dorp_lqs
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
