spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: sql_dev
    password: ved_lqs
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    # Only have this active once to create db-create.sql:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: db-create.sql
