# Orb 'circleci/maven@0.0.12' resolved to 'circleci/maven@0.0.12'
version: 2
jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
#      - run:
#          name: Spring Framework Guru had to do that
#          command: mvn install -DskipTests
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
#      TODO: make cobertura work
#      - run:
#          name: Integration test and code coverage
#          command: mvn integration-test cobertura:cobertura
      - store_test_results:
          path: target/surefire-reports
#      - run:
#          name: Send to CodeCov
#          command: bash <(curl -s https://codecov.io/bash)
workflows:
  maven_test:
    jobs:
      - maven/test
  version: 2

# Original config.yml file:
# version: 2.1
#
# orbs:
#   maven: circleci/maven@0.0.12
#
# workflows:
#   maven_test:
#     jobs:
#       - maven/test # checkout, build, test, and upload test results
